name: LLM Scout Agent

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: 'false'
        type: boolean
      branch:
        description: 'Branch to use'
        required: false
        default: 'feature/expand-to-9-providers'
        type: string

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch || 'feature/expand-to-9-providers' }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'scout-agent/package.json'
    
    - name: Install dependencies
      run: |
        cd scout-agent
        npm install
    
    - name: Create environment file
      run: |
        cd scout-agent
        cat > .env << EOF
        BACKEND_URL=${{ secrets.BACKEND_URL }}
        AGENT_AUTH_TOKEN=${{ secrets.AGENT_AUTH_TOKEN }}
        HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
        EOF
    
    - name: Run LLM discovery
      run: |
        cd scout-agent
        npm run start
      env:
        BACKEND_URL: ${{ secrets.BACKEND_URL }}
        AGENT_AUTH_TOKEN: ${{ secrets.AGENT_AUTH_TOKEN }}
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
    
    - name: Upload discovery results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: discovery-results-${{ github.run_number }}
        path: scout-agent/output/
        retention-days: 30
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `LLM Scout Agent failed - Run #${{ github.run_number }}`,
            body: `
            The LLM Scout Agent workflow failed.
            
            **Run Details:**
            - Run ID: ${{ github.run_id }}
            - Run Number: ${{ github.run_number }}
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}
            - Triggered by: ${{ github.event_name }}
            
            **Action Required:**
            Please check the workflow logs and fix any issues.
            
            **Logs:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            `,
            labels: ['bug', 'scout-agent', 'ci-failure']
          });
          
          console.log('Created issue:', issue.data.html_url);
    
    - name: Log success
      if: success()
      run: |
        echo "LLM Scout Agent completed successfully"
        echo "Run ID: ${{ github.run_id }}"
        echo "Timestamp: $(date -u)"