name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Make scripts executable
      run: |
        chmod +x 700_scripts/705_build_release.sh
        chmod +x 300_implementation/askme-cli/gradlew
        
    - name: Build release
      run: |
        700_scripts/705_build_release.sh ${{ steps.get_version.outputs.VERSION }}
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ steps.get_version.outputs.VERSION }}" \
          --title "AskMe CLI v${{ steps.get_version.outputs.VERSION }}" \
          --notes "## 🚀 AskMe CLI v${{ steps.get_version.outputs.VERSION }}
        
        ### Quick Install
        \`\`\`bash
        curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
        \`\`\`
        
        ### What's New
        - Intelligent AI provider selection
        - Support for Google Gemini, Mistral AI, OpenAI, and Anthropic
        - Performance tracking and optimization
        - One-click installation
        - Privacy-first architecture with zero data collection
        
        ### Download
        - **Recommended**: Use the one-click installer above
        - **Manual**: Download the tar.gz file below
        
        ### Documentation
        - [Installation Guide](https://github.com/${{ github.repository }}/blob/main/500_release/507_development_setup.md)
        - [User Guide](https://github.com/${{ github.repository }}/blob/main/500_release/505_user_guide.md)
        - [API Documentation](https://github.com/${{ github.repository }}/blob/main/500_release/506_api_docs.md)" \
          ./dist/askme-cli-v${{ steps.get_version.outputs.VERSION }}.tar.gz \
          ./dist/askme-cli-v${{ steps.get_version.outputs.VERSION }}.sha256
