name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.3.0

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Make scripts executable
      run: |
        chmod +x 300_implementation/askme-cli/gradlew
        
    - name: Build CLI
      run: |
        cd 300_implementation/askme-cli
        ./gradlew clean cliApp:installDist
        
    - name: Create distribution
      run: |
        cd 300_implementation/askme-cli/cliApp/build/install
        
        # Create distribution directory
        mkdir -p askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}
        cp -r cliApp/* askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/
        
        # Create README for distribution
        cat > askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/README.md << 'EOF'
        # AskMe CLI - 5 Provider Edition v${{ steps.get_version.outputs.VERSION }}
        
        🤖 **Multi-Provider AI CLI Tool**
        
        ## Quick Start
        
        ```bash
        # Ask a question
        ./bin/cliApp "What is machine learning?"
        
        # Interactive mode  
        ./bin/cliApp
        
        # Show provider statistics
        ./bin/cliApp --stats
        ```
        
        ## ✅ Supported Providers (5)
        
        - **Google** - Gemini models
        - **Mistral** - Code generation
        - **Cohere** - Conversational AI
        - **Groq** - Ultra-fast inference
        - **OpenRouter** - Unified access
        
        ## 🔧 Requirements
        
        - Java 8+ (for Kotlin runtime)
        - Internet connection
        
        ---
        *Built with ❤️ using Kotlin + Ktor*
        EOF
        
        # Create archives
        tar -czf askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/
        zip -r askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.zip askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/
        
        # Generate checksums
        sha256sum askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz > askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz.sha256
        sha256sum askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.zip > askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.zip.sha256
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd 300_implementation/askme-cli/cliApp/build/install
        
        gh release create "v${{ steps.get_version.outputs.VERSION }}" \
          --title "AskMe CLI 5-Provider Edition v${{ steps.get_version.outputs.VERSION }}" \
          --notes "## 🚀 AskMe CLI v${{ steps.get_version.outputs.VERSION }}
        
        ### 🎯 5 Provider Support
        - **Google** - Gemini models (general, math, analysis)
        - **Mistral** - Code generation, technical queries  
        - **Cohere** - Conversational AI, reasoning
        - **Groq** - Ultra-fast inference
        - **OpenRouter** - Unified model access
        
        ### 🚀 Quick Install
        \`\`\`bash
        # Download and extract
        wget https://github.com/${{ github.repository }}/releases/download/v${{ steps.get_version.outputs.VERSION }}/askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz
        tar -xzf askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz
        chmod +x askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/bin/cliApp
        \`\`\`
        
        ### 🎯 Usage
        \`\`\`bash
        # Basic usage
        ./askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/bin/cliApp \"What is AI?\"
        
        # Interactive mode
        ./askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/bin/cliApp
        
        # Provider statistics
        ./askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}/bin/cliApp --stats
        \`\`\`
        
        ### 🔧 Requirements
        - Java 8+ (tested with Java 17)
        - Internet connection
        
        ### 📁 Download Options
        - **TAR.GZ**: Recommended for Linux/macOS
        - **ZIP**: Alternative format
        - **Checksums**: SHA256 verification included" \
          askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz \
          askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.zip \
          askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.tar.gz.sha256 \
          askme-cli-5-providers-v${{ steps.get_version.outputs.VERSION }}.zip.sha256