#!/bin/bash

# LLM Discovery Data Export Script
# This script runs the discovery and exports data locally

set -e

echo "🤖 Starting LLM Discovery and Export..."

# Create output directories
mkdir -p output
mkdir -p data/exports
mkdir -p data/reports

# Run the discovery (if not already done)
if [ ! -f "output/latest-discovery.json" ]; then
    echo "📡 Running LLM discovery..."
    npm start
else
    echo "📄 Using existing discovery data..."
fi

# Convert to CSV and Markdown
echo "📊 Converting data to CSV and Markdown..."
node scripts/json-to-csv.js

# Copy to data directory with timestamp
TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M-%S")
echo "⏰ Creating timestamped exports for: $TIMESTAMP"

# Copy latest files
cp output/llm-models.csv data/exports/llm-models-latest.csv
cp output/discovery-summary.md data/reports/discovery-summary-latest.md
cp output/latest-discovery.json data/exports/llm-discovery-latest.json

# Create timestamped copies
cp output/llm-models.csv "data/exports/llm-models-$TIMESTAMP.csv"
cp output/discovery-summary.md "data/reports/discovery-summary-$TIMESTAMP.md"
cp output/latest-discovery.json "data/exports/llm-discovery-$TIMESTAMP.json"

# Generate data directory README
cat > data/README.md << 'EOF'
# LLM Discovery Data

This directory contains automated LLM discovery data generated by the scout agent.

## Structure

- `exports/` - CSV and JSON data files
  - `llm-models-latest.csv` - Latest discovered models in CSV format
  - `llm-discovery-latest.json` - Latest raw JSON data
  - `llm-models-YYYY-MM-DD_HH-MM-SS.csv` - Timestamped exports
  - `llm-discovery-YYYY-MM-DD_HH-MM-SS.json` - Timestamped raw data

- `reports/` - Markdown summary reports
  - `discovery-summary-latest.md` - Latest summary report
  - `discovery-summary-YYYY-MM-DD_HH-MM-SS.md` - Timestamped reports

## Usage

The CSV files can be imported into spreadsheet applications or data analysis tools.
The JSON files contain the complete raw data with metadata.
The markdown reports provide human-readable summaries.

## Last Updated

EOF

date -u >> data/README.md

echo "✅ Export completed successfully!"
echo ""
echo "📁 Generated files:"
echo "   📄 data/exports/llm-models-latest.csv"
echo "   📄 data/reports/discovery-summary-latest.md"
echo "   📄 data/exports/llm-discovery-latest.json"
echo ""
echo "📦 Timestamped files:"
echo "   📄 data/exports/llm-models-$TIMESTAMP.csv"
echo "   📄 data/reports/discovery-summary-$TIMESTAMP.md"
echo "   📄 data/exports/llm-discovery-$TIMESTAMP.json"
echo ""

# Display summary
if [ -f "output/latest-discovery.json" ]; then
    TOTAL_MODELS=$(jq '.metadata.totalModels' output/latest-discovery.json 2>/dev/null || echo "unknown")
    SOURCES=$(jq -r '.metadata.sources | join(", ")' output/latest-discovery.json 2>/dev/null || echo "unknown")
    echo "📊 Summary:"
    echo "   🔢 Total Models: $TOTAL_MODELS"
    echo "   🏷️  Sources: $SOURCES"
    echo "   📅 Timestamp: $(jq -r '.metadata.timestamp' output/latest-discovery.json 2>/dev/null || echo "unknown")"
fi

echo ""
echo "🚀 To commit to git:"
echo "   git add data/"
echo "   git commit -m '📊 LLM Discovery Update - $(date -u)'"
echo "   git push"